### PR TITLE
feat: withdraw delegator reward

### PR DESCRIPTION
**Pull request by hikaruNagamine**
@YasunoriMATSUOKA  
Please review.

- Added Withdraw Delegator Reward button to Delegate Menu dialog.
withdraw-delegator-reward

Points you would like to discuss
- I am adding a "Withdraw Delegator Reward" process to the source file with the referenced createDelegate method.
Please consider whether it would be better to split this into a separate source like distribution.service.ts.
 staking.application.service.ts
 staking.service.ts
 ->
distribution.application.service.ts
distribution.service.ts

### CODE REVIEW

**Review by YasunoriMATSUOKA — COMMENTED** [review]
@hikaruNagamine 
> Points you would like to discuss
> 
> I am adding a "Withdraw Delegator Reward" process to the source file with the referenced createDelegate method.
> Please consider whether it would be better to split this into a separate source like distribution.service.ts.
> staking.application.service.ts
> staking.service.ts
> ->
> distribution.application.service.ts
> distribution.service.ts

I agree with the above policy.
Can you refactor from this PR's feature from `staking.*.service.ts` to `distribution.*.service.ts` in this PR? (The file is too large and another developer is implementing the same file in `staking.*.service.ts` currently and it is looking like there may be some conflicts. So we wanna avoid the conflicts to divide this PR's feature to another file like `distribution.*.service.ts` files.)
Thank you for your proposal.

**Comment by hikaruNagamine** [comment]
@YasunoriMATSUOKA 

> Can you refactor from this PR's feature from staking.*.service.ts to distribution.*.service.ts in this PR?

I got it.
I will try refactoring.
Thank you very much.

**Comment by hikaruNagamine** [comment]
@YasunoriMATSUOKA 
Please review.
🙇‍♂️

- [refactor: staking.*.service.ts -> distribution.*.service.ts](https://github.com/UnUniFi/web-apps/pull/196/commits/b1eb02241d8e6797fa88c68e1085884e2e81c787)

  > Can you refactor from this PR's feature from staking..service.ts to distribution..service.ts in this PR?

- [feat: show claimable delegator reward](https://github.com/UnUniFi/web-apps/pull/196/commits/8a8ba2aeefe67ab9c5979cc063a26f7a806b35ef)
  Added display of rewards in the dialog.
  https://www.notion.so/cauchye/show-claimable-delegator-reward-31e71569c9b64498b1181774e71fa7dc

**Review by YasunoriMATSUOKA — CHANGES_REQUESTED** [review]
@hikaruNagamine 
The api response for the amount of reward that can be withdrawn has a decimal point, but the amount actually withdrawn seems to be a truncated integer value.
I thought it would be less confusing to users if you modified the response to show the integer value of the amount actually withdrawn, so please modify it that way 🙏 
image
Other than that, LGTM.

**Comment by hikaruNagamine** [comment]
@YasunoriMATSUOKA 
> The api response for the amount of reward that can be withdrawn has a decimal point, but the amount actually withdrawn seems to be a truncated integer value.

I'm sorry.
I was omitted from consideration.
I have changed it to "Yes" because it is easier to count with a digit separator.
I also made a correction without, but after comparing the two, I decided to go with this one.

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
