### PR TITLE
Feature/staking page

### PR DESCRIPTION
**Pull request by Senna46**
# Changes
The implementation of a page where a list of validators and delegations to them.
- Change validator list design and detail page
- Add routing /delegate
- Proposal list and detail page
- Add routing /vote

### Delegate

- [x] delegate Dialog
- [x] delegate button
- [ ] change delegator button
- [ ] delete delegate button 

### Vote
- [ ] vote dialog
- [ ] vote button
- [ ] active button

### CODE REVIEW

**Comment by YasunoriMATSUOKA** [comment]
I guess routing should be /delegate. not /staking.

**Comment by Senna46** [comment]
I see that you have already created a staking, what is this?

**Comment by YasunoriMATSUOKA** [comment]
Probably we have already discussed about this today, but I left a memo.

> I see that you have already created a StakingModule, what is this?

It is a hidden page for special user. We want to divide delegate feature page from that page for special user.

**Comment by Senna46** [comment]
I add vote component, but i will create only delegate dialog and new delegate Tx in this PR.
Other function will be developed other PRs soon.

**Comment by Senna46** [comment]
Complete delegate dialog
スクリーンショット 2022-04-13 184711

**Comment by Senna46** [comment]
Routing Memo
- Delegate Component
  - delegate-menu-dialog
    - delegate-validator-dialog
    - chage-deligate-dialog
    - delete-delegate-dialog

**Comment by Senna46** [comment]
- view info
https://user-images.githubusercontent.com/29295263/163358371-997f85a4-01bc-4819-b404-f37dcec10f89.mp4

- delegate
https://user-images.githubusercontent.com/29295263/163358437-5cb48709-26af-45f9-90ec-e015d1925d97.mp4

But
```
An error has occur: Tx simulation failed: Error: Request failed with status code 400
```

**Comment by Senna46** [comment]
@YasunoriMATSUOKA 
plz review

- branch menu dialog
スクリーンショット 2022-04-14 191510

- delegate form
スクリーンショット 2022-04-14 191535

- delegate tx detail
スクリーンショット 2022-04-14 191010

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
