### PR TITLE
fix: readme about new test net

### PR DESCRIPTION
**Pull request by YasunoriMATSUOKA**
@yutaro-elk @mkXultra 
plz review 🙏

### CODE REVIEW

**Comment by yutaro-elk** [comment]
Is it ok to ignore that CI is down?

**Comment by YasunoriMATSUOKA** [comment]
Oh, I will check it. Thank you. But why?

**Comment by YasunoriMATSUOKA** [comment]
Once all CI failed, but I ran it again and it seems to have succeeded...

I am not sure of the cause, but the changes are only rewriting the contents of README.md, so I thought it might not be a problem.

**Review by yutaro-elk — APPROVED** [review]
LGTM

**Pull request merged**
