### PR TITLE
Refactor/vote dialogs use daisyui

### PR DESCRIPTION
**Pull request by hikaruNagamine**
## Corrections addressed in this PR
- angular/material -> daisy ui
- Delete angular/material

## review point
Check the results of DaysiUI support in the following UI.
If there is any part of the design that is not good looking, please point it out.
- vote
  - vote-form-dialog
  - deposit-form-dialog

### CODE REVIEW

**Comment by hikaruNagamine** [comment]
@Senna46 
DaisyUI is now supported. Please review.

Regarding the dialog close button on mobile displays, we are using DaisyUI to remove the MaterialModule.
If this fix is ok, we would like to fix other dialog close buttons as well.
https://github.com/UnUniFi/web-apps/pull/475/commits/922d951b1e343895d56b14a8b2e6806a8a6ef34c

**Comment by Senna46** [comment]
I would like to use mat-icon at present as there is no other good set of icons.
Now use mat-icon like any other Dialog. No problem to import MaterialModule for that.

**Review by Senna46 — APPROVED** [review]
Fixed dialog by #485 
After CI, this PR will be merged.

**Review by Senna46 — APPROVED** [review]
[LGTMeow](https://lgtmeow.com)

**Pull request merged**
