### PR TITLE
Sample to split logic from component to use case service

### PR DESCRIPTION
**Pull request by yutaro-elk**

### CODE REVIEW

**Comment by yutaro-elk** [comment]
@YasunoriMATSUOKA 
For ease of testing, I intend to proceed with the separation into "services" like this. Do you have any opinions?

I will refactor the use case service a little more

**Comment by YasunoriMATSUOKA** [comment]
@yutaro-elk 
Great works!
I have no objection to this as a first step.
Thank you!

**Comment by yutaro-elk** [comment]
@YasunoriMATSUOKA 
plz review in your good time.

-  `CosmosRestService` may be split in the future
- I wanted to add a test for usecase, but I concentrated on splitting once.

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
