### PR TITLE
feat: keplr gov

### PR DESCRIPTION
**Pull request by Ryo0731**
This PR enables you to use Keplr wallet with Voting / Depositing function.

- [x] Vote

- [x] Deposit

- Removed keplr wallets in ununifi select dialog.
- Fixed a bug when connecting to keplr wallet.
- Fixed a bug when voting No with veto/ No/ abstain

### CODE REVIEW

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 @Ryo0731 
I would like you to merge the keplr and txCommonService implementations into the dev as soon as possible. (feature/keplr-gov -> feature/keplr -> develop)

For this purpose, for example, keplr's vote can be implemented and debugged later.

**Comment by Senna46** [comment]
@YasunoriMATSUOKA #129 already merged to develop. The destination branch of this PR seems to be wrong.

@Ryo0731 feature/keplr already merged into develop, so this PR will merge into develop, plz.

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 
Oh, now, you changed the target branch, maybe I understand situation changed.
It's OK.
Ignore the following comments.
https://github.com/UnUniFi/web-apps/pull/159#issuecomment-1124868510

**Review by Senna46 — APPROVED** [review]
[LGTMeow](https://lgtmeow.com)

**Pull request merged**
