### PR TITLE
Landing page __ feat: change base branch from main to develop #705

### PR DESCRIPTION
**Pull request by taro04**
change base branch to develop from main (#705)
please review it.

### CODE REVIEW

**Comment by Senna46** [comment]
@taro04 Did you implement only this page? https://ununifi-stable.web.app/education.html
The latest commit includes this HTML.

Do you have `About Gluon Earn` and `About Gluon Trade` ready?
https://www.figma.com/file/1UnZxWGSbTdysEtBxR9lHZ/Gluon-Landing-Page?type=design&node-id=0-1&mode=design&t=oEq5mE83L9pc3ZfY-0

I don't know the details about changing the Metadata and don't worry about it because I can do it.

**Comment by taro04** [comment]
Thank you for fixing flex.
I also understand about the html path.

Btw，I will request a review of Advance by 2/8.

**Comment by taro04** [comment]
The display is mostly complete.
There are some modifications to the behavior when pressing buttons.
I think it will be finished by the end of the week.

**Comment by taro04** [comment]
@Senna46 
please review "beginner" and "advance" page.

**Review by Senna46 — CHANGES_REQUESTED** [review]
Good job. I think the display above 1024px has been implemented without any problems.
But, there are some problems for the display < 768px.

### beginner
- [x] The numbered tabs are sticking out. Should adjust size or use `overflow-x-auto`.
- [x] Step 1 and images should be aligned vertically on mobile (sm). https://tailwindcss.com/docs/responsive-design

スクリーンショット 2024-02-13 185807

### advanced
- [ ] Advanced still has the same responsive problem.
- [x] `What is Gluon Trade?` duplicated.
- [x] I think the Level section needs to be designed for mobile, so I'll ask Javier to do that.

**Comment by taro04** [comment]
@Senna46 
Thank you for your view. Beginner page is fixed.
I will fix advanced page after decided the mobile design.

**Comment by Senna46** [comment]
LGTM
For beginners, fine.

**Comment by taro04** [comment]
@Senna46 
The corrections you commented have been completed. 
(I will adjust the font size of order of each section a little more.)

**Review by Senna46 — APPROVED** [review]
LGTM!
This is good for mobile support.
[LGTMeow](https://lgtmeow.com)

**Comment by taro04** [comment]
> @Senna46 The corrections you commented have been completed. (I will adjust the font size of order of each section a little more.)

@Senna46 
Thank you for review.
I adjusted the font size and some figs.

**Comment by Senna46** [comment]
OK, Thanks

**Pull request merged**
