### PR TITLE
feat: new landing page

### PR DESCRIPTION
**Pull request by taro04**

### CODE REVIEW

**Comment by taro04** [comment]
@YasunoriMATSUOKA 
Please review.

I checked below.
- drawer open/ close.
- jump to home/ abput/ community sections.
- push the [LAUNCH APP] button to jump to /portal
- push the [WHITEPAPER] button to download the white-paper


image

**Review by YasunoriMATSUOKA — CHANGES_REQUESTED** [review]
@KimuraYu45z @ThetaShis @kazukikanehara 
The red areas in the following screenshot need some draft text. Plz prepare and notify to @taro04 .
ununifi-lp-about-comment-should-be-properly-set

@taro04 
I guess twitter and discord link is not enabled. Plz enable them.

**Comment by YasunoriMATSUOKA** [comment]
@taro04 
1. I guess text content is fixed as follows. So plz fix them 🙏 

```
1. Deposit NFT into vault
You can deposit your NFT as collateral, and the NFT will be listed on the marketplace. Prospective buyers of that NFT can make a bid. If you accept the bid, you can sell it. The NFT will not be settled without your permission and you will not lose the NFT.

2. Mint stablecoins & Auto DeFi Yield
You can issue stablecoins within the range of bids in the marketplace. UnUniFi can automatically operate the issued stablecoins and you can receive rewards.
```

2. I guess twitter and discord link is not enabled. Plz enable them 🙏 
3. If possible, I thought it would be better if there was a LAUNCH EXPLORER below or beside the LAUNCH APP button. However, I think this may be controversial, and if you do implement it, it would be helpful to have a separate commit so that this section can be revert.

**Comment by taro04** [comment]
@YasunoriMATSUOKA 
I checked below. Please review.

 - Jump to Twitter and Discord using the link
 - The description of 01 and 02 is in English

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Comment by YasunoriMATSUOKA** [comment]
This PR contains inappropriate commits, So This PR is closed.

**Pull request closed without merging**
