### PR TITLE
feat: block details page

### PR DESCRIPTION
**Pull request by taro04**
- Done
add Item / add back & forward button

- Todo
- [x] get transaction from block (` .getTxsEvent(sdk.rest, [tx.height='${height}']) `)

image

### CODE REVIEW

**Comment by taro04** [comment]
@YasunoriMATSUOKA 
Please review.
get transaction from block.

image

As you commented, displayed item of tx is for only transfer tx.
But, I want to close this pull request and follow above problem at the Issue

**Comment by YasunoriMATSUOKA** [comment]
@taro04 
I think it is more simple to create the following type data in pages component.

```ts
{
  hash: string;
  type: string;
  from: string;
  to: string;
  amount: string;
}

```

I think it's ok that from, to and total amount are not supported currently. 
But, I think tx type should be shown at least the following list tx type.

- staking
  - [ ] cosmos.staking.v1beta1.MsgCreateValidator
  - [ ] cosmos.staking.v1beta1.MsgDelegate
  - [ ] cosmos.staking.v1beta1.MsgBeginRedelegate
  - [ ] cosmos.staking.v1beta1.MsgUndelegate
  - [ ] cosmos.gov.v1beta1.MsgSubmitProposal
  - [ ] cosmos.gov.v1beta1.MsgDeposit
  - [ ] cosmos.gov.v1beta1.MsgVote
  - [ ] cosmos.bank.v1beta1.MsgSend

I think you can use tx.body.messages.map((message) => message.@type).join() as tx type.

<details>
```json
{
  "tx": {
    "body": {
      "messages": [
        {
          "@type": "/cosmos.bank.v1beta1.MsgSend",
          "from_address": "ununifi1zxjvkcslr38fm6da000ac5lx8jerf0mcg4cxh6",
          "to_address": "ununifi16l9hprx5w2vz760zjg9xffa3c4a8s8547f9q4f",
          "amount": [
            {
              "denom": "ubtc",
              "amount": "100"
            },
            {
              "denom": "uguu",
              "amount": "970000"
            }
          ]
        }
      ],
      "memo": "",
      "timeout_height": "0",
      "extension_options": [
      ],
      "non_critical_extension_options": [
      ]
    },
    "auth_info": {
      "signer_infos": [
        {
          "public_key": {
            "@type": "/cosmos.crypto.secp256k1.PubKey",
            "key": "A8h4MPjtVBawy7TVYEG0pUbk4sPmVA8DAgEOVTm6s2K4"
          },
          "mode_info": {
            "single": {
              "mode": "SIGN_MODE_DIRECT"
            }
          },
          "sequence": "5"
        }
      ],
      "fee": {
        "amount": [
          {
            "denom": "uguu",
            "amount": "56009"
          }
        ],
        "gas_limit": "77790",
        "payer": "",
        "granter": ""
      }
    },
    "signatures": [
      "CjI6F8LWq9bN3MEYIPkB8Ol5CLXyw4L/wu9+QGDY1qZeHm/mBOUjHr6s2JYDS1VKjFG8cwSZUhp4F8NURVX9gw=="
    ]
  },
  "tx_response": {
    "height": "1924527",
    "txhash": "1EA8607C3F258282F83E2A80A5FB34EB09F232DF164351B5B1870EBF4AD2DB3B",
    "codespace": "",
    "code": 0,
    "data": "0A060A0473656E64",
    "raw_log": "[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"send\"},{\"key\":\"sender\",\"value\":\"ununifi1zxjvkcslr38fm6da000ac5lx8jerf0mcg4cxh6\"},{\"key\":\"module\",\"value\":\"bank\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"ununifi16l9hprx5w2vz760zjg9xffa3c4a8s8547f9q4f\"},{\"key\":\"sender\",\"value\":\"ununifi1zxjvkcslr38fm6da000ac5lx8jerf0mcg4cxh6\"},{\"key\":\"amount\",\"value\":\"100ubtc,970000uguu\"}]}]}]",
    "logs": [
      {
        "msg_index": 0,
        "log": "",
        "events": [
          {
            "type": "message",
            "attributes": [
              {
                "key": "action",
                "value": "send"
              },
              {
                "key": "sender",
                "value": "ununifi1zxjvkcslr38fm6da000ac5lx8jerf0mcg4cxh6"
              },
              {
                "key": "module",
                "value": "bank"
              }
            ]
          },
          {
            "type": "transfer",
            "attributes": [
              {
                "key": "recipient",
                "value": "ununifi16l9hprx5w2vz760zjg9xffa3c4a8s8547f9q4f"
              },
              {
                "key": "sender",
                "value": "ununifi1zxjvkcslr38fm6da000ac5lx8jerf0mcg4cxh6"
              },
              {
                "key": "amount",
                "value": "100ubtc,970000uguu"
              }
            ]
          }
        ]
      }
    ],
    "info": "",
    "gas_wanted": "77790",
    "gas_used": "70898",
    "tx": {
      "@type": "/cosmos.tx.v1beta1.Tx",
      "body": {
        "messages": [
          {
            "@type": "/cosmos.bank.v1beta1.MsgSend",
            "from_address": "ununifi1zxjvkcslr38fm6da000ac5lx8jerf0mcg4cxh6",
            "to_address": "ununifi16l9hprx5w2vz760zjg9xffa3c4a8s8547f9q4f",
            "amount": [
              {
                "denom": "ubtc",
                "amount": "100"
              },
              {
                "denom": "uguu",
                "amount": "970000"
              }
            ]
          }
        ],
        "memo": "",
        "timeout_height": "0",
        "extension_options": [
        ],
        "non_critical_extension_options": [
        ]
      },
      "auth_info": {
        "signer_infos": [
          {
            "public_key": {
              "@type": "/cosmos.crypto.secp256k1.PubKey",
              "key": "A8h4MPjtVBawy7TVYEG0pUbk4sPmVA8DAgEOVTm6s2K4"
            },
            "mode_info": {
              "single": {
                "mode": "SIGN_MODE_DIRECT"
              }
            },
            "sequence": "5"
          }
        ],
        "fee": {
          "amount": [
            {
              "denom": "uguu",
              "amount": "56009"
            }
          ],
          "gas_limit": "77790",
          "payer": "",
          "granter": ""
        }
      },
      "signatures": [
        "CjI6F8LWq9bN3MEYIPkB8Ol5CLXyw4L/wu9+QGDY1qZeHm/mBOUjHr6s2JYDS1VKjFG8cwSZUhp4F8NURVX9gw=="
      ]
    },
    "timestamp": "2022-04-20T13:34:41Z"
  }
}
```
</details>

**Review by YasunoriMATSUOKA — CHANGES_REQUESTED** [review]
@taro04 
plz check https://github.com/UnUniFi/web-apps/pull/66#issuecomment-1104000926 🙏

**Comment by taro04** [comment]
@YasunoriMATSUOKA 
Please review.
The type of transactions in the block is acquired by `＠type` and displayed it.

image

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
