### PR TITLE
feat: refactor and enable keplr

### PR DESCRIPTION
**Pull request by YasunoriMATSUOKA**
@mkXultra @Senna46 
plz review 🙏 
refactor and enable keplr.

- Remove unnecessary service and dialog.
- Integrate metamask related implementation to infrastructure service with DIP pattern.
- Move keplr related service under wallet directory

ununifi-connect-keplr-and-send-delegate-tx-sample_20220602

### CODE REVIEW

**Comment by Senna46** [comment]
Some bugs in error handling were found. It may be an issue with my codes.

- When Keplr was already set up (OK)
success

- When Keplr was installed, but NOT logged in
Get an error, but we don't know the details.
close

- When Keplr was NOT installed.
Error window appears doubly.
error

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 cc: @mkXultra 
I wanna ask you to fix these bugs. Is it OK?

**Comment by Senna46** [comment]
If you are not in a hurry, it is OK. I will most likely not be able to do this today or tomorrow.

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 
I understand. If I can, I will fix them. Thank you.

**Comment by YasunoriMATSUOKA** [comment]
Fix the issue https://github.com/UnUniFi/web-apps/pull/200#issuecomment-1144444835 later.
I will merge this and deploy to alpha-test environment.

**Pull request merged**
