### PR TITLE
feat: handle create-validator for multiple validators in the portal app

### PR DESCRIPTION
**Pull request by peterblockman**
* Allow uploading multiple wallet-backup files, and broadcast multiple create-validator transactions
* Add Graphql module in the portal app
* Add options parameter to createValidatorSimple. This enables handling errors on the component level

### CODE REVIEW

**Review by YasunoriMATSUOKA — CHANGES_REQUESTED** [review]
@peterblockman 
Thank you for your Great Works!
But, this PR is conflicted...
Can you resolve conflict?

**Comment by peterblockman** [comment]
> @peterblockman Thank you for your Great Works! But, this PR is conflicted... Can you resolve conflict?

Resolved https://github.com/UnUniFi/web-apps/pull/166/commits/42557fa7dc6504324133e7764e76b8c7d9fff129 @YasunoriMATSUOKA

**Comment by YasunoriMATSUOKA** [comment]
@peterblockman 
I reviewed your PR with code only and it seems to be fine.

But, if I can, I wanna debug it with sending tx actually. 
I guess appropriate userId contained URL is necessary for debug.
If there is no problem, I would like to debug it with an appropriate URL (contains appropriate userId)  and  the node-6 node to become a validator.

Can you please tell me the URL( contains appropriate userId)?

But, If that needs a lot of tasks or causes security concerns, it may not be necessary.
How do you think about it?

Thank you for your gread works!

**Comment by YasunoriMATSUOKA** [comment]
@peterblockman 
I have created the reference PR https://github.com/UnUniFi/web-apps/pull/172 to resolve problem with work around way.

**Comment by peterblockman** [comment]
@YasunoriMATSUOKA it was due to commission values unit conversion. I pushed the fix: https://github.com/UnUniFi/web-apps/pull/166/commits/e47ff07c7fc7c29b84ee529f63bd1263a8ad01c7.  Following your [recommendation](https://github.com/UnUniFi/web-apps/pull/166#issuecomment-1128469106):

1. I added [disableSimulate](https://github.com/peterblockman/web-apps/blob/e47ff07c7fc7c29b84ee529f63bd1263a8ad01c7/projects/portal/src/app/models/cosmos/staking.application.service.ts#L30) option, so we can turn it on/off. 
2. Allow sending transactions without a fee: [handleSimulateToCreateValidator](https://github.com/peterblockman/web-apps/blob/e47ff07c7fc7c29b84ee529f63bd1263a8ad01c7/projects/portal/src/app/models/cosmos/staking.application.service.ts#L82)
4. I used [bignumber.js](https://mikemcl.github.io/bignumber.js/) to handle calculation and decimal places in [makeComissionValues](https://github.com/peterblockman/web-apps/blob/e47ff07c7fc7c29b84ee529f63bd1263a8ad01c7/projects/portal/src/app/models/cosmos/staking.service.ts#L81). I believe that sooner or later we will need that lib to handle number in this web-apps.

I think there is an inconsistency between `simulateToCreateValidator` and `createValidator` that needed more further debugging.

**Comment by YasunoriMATSUOKA** [comment]
@peterblockman 
Great works!

I confirmed tx has been sent successfully.

Debug URL: http://127.0.0.1:5000/portal/staking/create-validator/multiple?userId=6aaf4f84-a6ab-4626-ac03-86efef404d7d
Tx: http://127.0.0.1:5000/explorer/txs/EEE8AED33F10A09D3D779D13D8DD822D459108CA00F4DF5EF94C165B68479C09
Validator: http://127.0.0.1:5000/explorer/validators/ununifivaloper1p3gxwlyes9ccahgxn02uknwl7cdqff8ek0ve0l
Screenshot
ununifi-create-validator-multiple-20220517

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
