### PR TITLE
Arrayed Configs support

### PR DESCRIPTION
**Pull request by Senna46**

### CODE REVIEW

**Comment by Senna46** [comment]
# Status Report
- Support for Configs list
- Implement Change Node pull-down list

## To Do
Switch to selected node
（Now, not async, log only ）

**Comment by Senna46** [comment]
@YasunoriMATSUOKA 
Implemented async node switching.
Is it safe to proceed with the work as is? Please confirm.

https://github.com/UnUniFi/web-apps/pull/40/commits/2c8f1e1e7aa05a7f0e851a7d610ce2153ad13a1c
The node to switch to is flushed as BehaviorSubject and made Observable in config.service.
Each component uses this Observable to async use the value of config.

**Comment by YasunoriMATSUOKA** [comment]
I will check it now, wait a moment plz 🙏

**Comment by YasunoriMATSUOKA** [comment]
Great works! 
The implementation is OK!

This is a matter of preference, but I think configTypeOptions-like name would be good for configOptions or configs.
I think it would be less confusing to use configType as config too.

Thank you!

**Review by YasunoriMATSUOKA — CHANGES_REQUESTED** [review]
> This is a matter of preference, but I think configTypeOptions-like name would be good for configOptions or configs.
> I think it would be less confusing to use configType as config too.

Did you check that?
I think it's not a type so it should be changd...

**Comment by Senna46** [comment]
Changes are complete.
I debugged the config switching only on the top page. Other pages cannot be judged immediately.

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
