### PR TITLE
feat: Add the parse function to extract common elements of the tx

### PR DESCRIPTION
**Pull request by taro04**
@YasunoriMATSUOKA 

Please review.
I extracted the information from tx.
7/15 types of tx were confirmed. I haven't reached any other types of tx.
I think it's enough to check with some types of tx.

But if you need to check for other types of tx, please tell me how to access that tx or the block height that contains the tx.
(Nothing appeared in the [gov] pull-down of explorer / transaction page.)

- debug
address
[http://localhost:4200/explorer/accounts/ununifi1wehequ8gcwnf6kredpen49re6qddylk23aepca](url)
MsgWithdrawDelegatorReward
[http://localhost:4200/explorer/blocks/492901](http://localhost:4200/explorer/blocks/492901)
MsgEditValidator
[http://localhost:4200/explorer/blocks/134970](url)
MsgCreateValidator
[http://localhost:4200/explorer/blocks/17517](url)
MsgUndelegate
[http://localhost:4200/explorer/blocks/492911](url)
MsgBeginRedelegate
[http://localhost:4200/explorer/blocks/492886](url)
MsgDelegate
[http://localhost:4200/explorer/blocks/135036](url)
MsgSend
[http://localhost:4200/explorer/blocks/65485](url)
(* chainID = 'create-validator-debug';)

image

### CODE REVIEW

**Comment by KimuraYu45z** [comment]
I think that...
using the table with same table heads, is unreasonable.
If there is some transaction type which is difficult to adapt this table heads (and I think there are many such transaction types), this UI will lead to be confusing or unreasonable UI.

So, the logic for parsing tx types is good. The remaining big problem is UI, I think.

**Comment by taro04** [comment]
> It is not possible to use a table with the same table head.

I think so. now, I still feel a lot of difficulty. (Especially `MsgWithdrawDelegatorReward` )

Then, should I change the table head to an item common to Tx? 
For example, BlockHeight, (Hash), MessageType, Time.

**Comment by taro04** [comment]
@YasunoriMATSUOKA, @KimuraYu45z


I would like to change the table header like this.

- tx in block page
image
- tx in account page
image
(Do you think need ”Height” here?)

Please let us know if you have any other ideas.

**Comment by KimuraYu45z** [comment]
齟齬無いように日本語で書きますが、

- これだとMsgSendが却って不便になる改悪になると思います。
- そもそもtableという構造がまずいんだとおもいます。

**Comment by taro04** [comment]
@YasunoriMATSUOKA, cc @KimuraYu45z 

Please, review. 🙏 
After that, I will implement parsing of the tx detail page.

- tx in address page
image

- tx in block page
image

**Comment by taro04** [comment]
WIP

- distribution
20220621_distribution

- gov
20220621_gov

- staking & send
20220621_staking send

Todo:
parse proposal.content
Some Tx do not match their type (MsgVoteWeighted／MsgCreateVestingAccount／MsgSetWithdrawAddress)

**Comment by taro04** [comment]
@YasunoriMATSUOKA 
I checked all type of  tx in detail page.
Please review. 🙏 

debug on chainID = 'ununifi-alpha-test-v2'
- MsgSend
http://localhost:4200/explorer/txs/AF78448BFBF4725FA9EF8382B52743210B6EBC3B02BE26C2BCB288202F0DE73B
- MsgCreateVestingAccount
http://localhost:4200/explorer/txs/1A43D1B11A996582F65E1F068B156F197875CC8DFD3B3EE3586EDC28E3F47687

- MsgWithdrawValidatorCommission
http://localhost:4200/explorer/txs/48FF804FB6C8F79BF9E4A70A81A983A7D56045C6FF42C6F98231559C5A2F5B99
- MsgWithdrawDelegatorReward
http://localhost:4200/explorer/txs/B85D9F6FEB764F582A5C39F6D39D3F1803CA7668A3E3025D68C41128952E634B
- MsgSetWithdrawAddress
http://localhost:4200/explorer/txs/AEEE3B0EE9D229CF9F873C63403630AB5610A3DCF7D212251AE80B098EC6F3B9
- MsgFundCommunityPool
http://localhost:4200/explorer/txs/3A26975A2241FC6C3FE2F94D1C013E627D5ABE5990FC1956178AF5F09A8F896B


- MsgDeposit
http://localhost:4200/explorer/txs/41DDF3BB9F1275163CEA9B168925E9410E1686A34ECEEDC58EBCEF81219423CD
- MsgSubmitProposal
http://localhost:4200/explorer/txs/8B21739E3568727D0C30E469910359643E2B85E88B0B223E644566692721F5D8
- MsgVoteWeighted
http://localhost:4200/explorer/txs/66CB9D610E6C65892FF9720534E1AB3D29068B4FF0EAA69554389BC45995205A
- MsgVote
http://localhost:4200/explorer/txs/0363D6FA41F145B375E14966E6AED59AC4016BBED8EB7EFA1CEB37149BC9D553

debug on chainID = 'create-validator-debug';

- MsgEditValidator
http://localhost:4200/explorer/txs/91C4D1417B0F0E75572F40CC3340B52296E656B0D01CE4FB17A69F359C0326E1
- MsgDelegate
http://localhost:4200/explorer/txs/4AA1538093588671AB4189624721FF35ADE6634F5ABACE5F66BE34C741ECC35D
- MsgBeginRedelegate
http://localhost:4200/explorer/txs/E1F1AE2CBC9C1EDA0C68943A71F4FE6FC7EA11CC0A68DCED9DF8E6D9EF5AC636
- MsgUndelegate
http://localhost:4200/explorer/txs/CAAB2DFD76C04697ED8AA9333845440D573218E5BCFEE7C6AA401717F8C69D4B
- MsgCreateValidator
http://localhost:4200/explorer/txs/4BAA998D593D96854C76B9067DA7A7235109D199FFE18AD73EA3D623E69223EF

However, I think this PR will be merged after conmos-client v0.46.0 is completely merged.

**Comment by YasunoriMATSUOKA** [comment]
@taro04 
Sorry, can you fix marketplace CI errors? (Unnecessary to debug marketplace (and shared) features. Only necessary to fix CI errors(=build errors).)

**Comment by taro04** [comment]
Sorry, unintentionally modifying the marketplace was also the cause of the CI error.

The build error is gone, but I'm updating Angular.json in this PR, so I think this PR should be merged after [#236](https://github.com/UnUniFi/web-apps/pull/236) merges.

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
