### PR TITLE
feat: portal cdp auction

### PR DESCRIPTION
**Pull request by Senna46**
This is a Pull Request to add UnUniFi functionality to the portal, Wallet functionality section.

To Do

- [x] CDP Create (Mint)
- [x] Auction

Side Nav
- Home
- Keys
- Send
- Delegate
- Vote
- Faucet (experimental)
- Mint
- Auction
- Monitor (experimental)

How about verbs and nouns, each of which should be displayed as a group?

### CODE REVIEW

**Comment by Senna46** [comment]
@YasunoriMATSUOKA 本PRでCDP機能とAuction機能をPortalに移行しています。動作確認してませんが、確認後のマージとした方が良いでしょうか
ルーティングと表示の確認のみし、cosmos, ununifi-clientが0.45.1で動作しない問題はIssueにあげています。

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 
Detailed debugging can be done later.
But, please make sure that the build passes.
If there are any temporary irregular implementations to make the build go through, please add comments to let us know.

**Comment by Senna46** [comment]
@YasunoriMATSUOKA 
Debugging will be conducted later. 
The build is confirmed to be OK. The error https://github.com/UnUniFi/web-apps/pull/8/commits/3cb83854204bcfd705aa170bfa6f364fe9fe149f was caused by an unused Flex-layout in the code.

How about I merge it, OK?

**Review by YasunoriMATSUOKA — APPROVED** [review]
@Senna46 
This PR LGTM! But I will handle following procedures. After that, I will merge them. Thank you 🙏 

These changes should be applied to not only main branch but develop branch.
So, we need to create PR with develop target branch from same branch.
- feat/portal-cdp-auction -> main
- feat/portal-cdp-auction -> develop

LGTM

**Pull request merged**
